hh_power <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
hh_power_feb1and2 <- subset(hh_power, Date %in% c("1/2/2007","2/2/2007"))
datetime <- with(hh_power_feb1and2, as.POSIXct(paste(Date, Time), format="%d/%m/%Y %H:%M:%S"))
plot(datetime, hh_power_feb1and2$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(datetime, hh_power_feb1and2$Sub_metering_2, type = "l", col="red")
points(datetime, hh_power_feb1and2$Sub_metering_3, type = "l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lwd=1,
       x.intersp = 0.75, y.intersp = 0.75, xjust=1, yjust=1)
dev.copy(png,"plot3.png")
dev.off()
