hh_power <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
hh_power_feb1and2 <- subset(hh_power, Date %in% c("1/2/2007","2/2/2007"))
datetime <- with(hh_power_feb1and2, as.POSIXct(paste(Date, Time), format="%d/%m/%Y %H:%M:%S"))
par(mfrow=c(2,2))
plot(datetime, hh_power_feb1and2$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(datetime, hh_power_feb1and2$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(datetime, hh_power_feb1and2$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(datetime, hh_power_feb1and2$Sub_metering_2, type = "l", col="red")
points(datetime, hh_power_feb1and2$Sub_metering_3, type = "l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), 
       lwd=0.6, bty="n", y.intersp = 0.5, xjust=1, yjust=1, inset=0)
plot(datetime, hh_power_feb1and2$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png,"plot4.png")
dev.off()
